### ISSUE TITLE
Can't add a sprite

### ISSUE THREAD

**Issue by ToshaEssential** [russomf/doodlepad#1]
Hello! I added the java class and the bird.png file to the root of the project. Nothing shows up after compiling. What am I doing wrong?

Screenshot - https://ibb.co/XJgvL6G

project/
. Move.java
. bird.png

```
import doodlepad.*;

import java.awt.*;

public class Move {

    public static void main(String[] args) {
        Pad pad = new Pad(600,600);
        Sprite bird = new Sprite("bird.png",50,50,190,5);
        pad.setTickHandler( (Pad p, long when) -> { bird.advance(); } );
        pad.setTickRate(10);
        pad.startTimer();
    }
}
```

**Comment by ToshaEssential** [comment]
https://ibb.co/XJgvL6G

**Comment by russomf** [comment]
Make sure to download the [doodlepad.jar](https://github.com/russomf/doodlepad/blob/master/dist/doodlepad.jar?raw=true) file and add it to your project folder. Then, while using a terminal with the current directory set to your project folder, compile and run:
```
javac -cp doodlepad.jar Move.java
java -cp .;doodlepad.jar Move
```
Your program works well.

**Comment by ToshaEssential** [comment]
It doesn't work. 
https://www.youtube.com/watch?v=8QPEaa-0ySY

**Comment by russomf** [comment]
Please try this:

```
import javax.swing.SwingUtilities;
import doodlepad.*;

public class Move 
{
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                Pad pad = new Pad(600,600);
                Sprite bird = new Sprite("bird.png",50,50,190,5);
                pad.setTickHandler( (Pad p, long when) -> { bird.advance(); } );
                pad.setTickRate(10);
                pad.startTimer();
            }
        });
    }
}
```

**Comment by ToshaEssential** [comment]
That didn't solve the problem either(
https://www.youtube.com/watch?v=FFzdZ9s_es4

**Comment by russomf** [comment]
Is there anything printed to the terminal?

**Comment by ToshaEssential** [comment]
No, it's empty there

**Comment by russomf** [comment]
This is difficult to debug without having some indication of what is going wrong, especially given that your programs are working for me. Here are a few additional things to try.

1. Instead of passing the String “bird.png” to the Sprite constructor, pass the full absolute path to the PNG file as the first argument.
2. Download the original sprite image file again from https://doodlepad.org/images/FlyingBird.png. Open the image file in an image editor to make sure it looks good. It should have dimensions 950 x 180 pixels, and you should see the five frames. 
3. After the window appears, resize it slightly. This will force a redraw.
4. If all that fails, I suggest you compile and run from the terminal, just to remove the IDE from the mix to check if some configuration setting is causing an unexpected problem.
    * Copy [doodlepad.jar](https://github.com/russomf/doodlepad/blob/master/dist/doodlepad.jar?raw=true) to your project directory. 
    * Make sure all files are present: `Move.java, bird.png, doodlepad.jar`
    * Open a terminal, and change to the project directory.
    * Compile: `javac -cp doodlepad.jar Move.java`
    * Run: `java -cp .;doodlepad.jar Move`
    * (Replace ";" with ":" if on a Mac or Linux)

Have you been able to get any program to run with the DoodlePad library, such as the MyFirstOval program on the first About page of https://doodlepad.org ?

**Comment by ToshaEssential** [comment]
I compiled and ran from the terminal in jdk 16 and everything worked!!! Thanks everything works now!!!!
https://ibb.co/wpcRMsr

**Comment by ToshaEssential** [comment]
One more question. Are there any plans to add new features to the library in the future? I read all the documentation on doodlepad.org and I loved it all!

**Comment by russomf** [comment]
I'm very glad to hear you got it working. I suspect it has something to do with an IDE setting that makes it think the "current directory" is different than the project directory.

I've used the library to teach introductory computing for many years. It's designed specifically to "just work." That's why you can write a program with one statement "Oval o = new Oval();" and get a window with an Oval that you can drag with the mouse. Doing this the way Swing was designed requires knowledge of all the Swing classes and how they work together. Also, students can write event-driven programs without having to understand interfaces, which is a topic not covered until the end of the first semester. Java's introduction of "method references" made this possible. I wrote a paper that describes the library design motivation. If you send me an email at russom at tcnj dot edu, I'll sent it to you.

Just recently I added several methods to the Shape class that let's you add a text label to any Shape. These are [setText()](https://doodlepad.org/dist/javadoc/doodlepad/Shape.html#setText(java.lang.String)), [getText()](https://doodlepad.org/dist/javadoc/doodlepad/Shape.html#getText()), and several related methods to change font, font size, font color etc. I was tired of having to create an additional Text shape, disable event handling, and place it over a Shape like Rectangle just to label it. It's not perfect (e.g. it doesn't wrap text) but it handles the most common scenarios.

I don't have specific plans for further enhancement at the moment, but let me know if you have ideas. My primary mission is to make it possible for people to write graphic programs without having to first master advanced concepts like inheritance and interfaces, and without having to understand in detail all the classes in the Swing library.

Best regards.
